In [27]:
f = open("data.txt", "r")
data = f.readline().split(',')
intcode = [int(x) for x in data]

intcode[1] = 12
intcode[2] = 2

In [28]:
i = 0
while intcode[i] != 99:
    instruction = intcode[i]
    pos1 = intcode[intcode[i+1]]
    pos2 = intcode[intcode[i+2]]
    if instruction == 1:
        val = pos1 + pos2
    else:
        val = pos1 * pos2
    intcode[intcode[i+3]] = val

    i += 4

In [29]:
intcode

[3654868,
 12,
 2,
 2,
 1,
 1,
 2,
 3,
 1,
 3,
 4,
 3,
 1,
 5,
 0,
 3,
 2,
 9,
 1,
 36,
 1,
 19,
 5,
 37,
 1,
 23,
 5,
 38,
 2,
 27,
 10,
 152,
 1,
 31,
 9,
 155,
 1,
 35,
 5,
 156,
 1,
 6,
 39,
 158,
 2,
 9,
 43,
 474,
 1,
 5,
 47,
 475,
 2,
 6,
 51,
 950,
 1,
 5,
 55,
 951,
 2,
 10,
 59,
 3804,
 1,
 63,
 6,
 3806,
 2,
 67,
 6,
 7612,
 2,
 10,
 71,
 30448,
 1,
 6,
 75,
 30450,
 2,
 79,
 9,
 91350,
 1,
 83,
 5,
 91351,
 1,
 87,
 9,
 91354,
 1,
 91,
 9,
 91357,
 1,
 10,
 95,
 91361,
 1,
 99,
 13,
 91366,
 2,
 6,
 103,
 182732,
 1,
 107,
 5,
 182733,
 1,
 6,
 111,
 182735,
 1,
 9,
 115,
 182738,
 1,
 119,
 9,
 182741,
 2,
 123,
 10,
 730964,
 1,
 6,
 127,
 730966,
 2,
 131,
 13,
 3654830,
 1,
 13,
 135,
 3654835,
 1,
 9,
 139,
 3654838,
 1,
 9,
 143,
 3654841,
 1,
 147,
 13,
 3654846,
 1,
 151,
 9,
 3654849,
 1,
 155,
 13,
 3654854,
 1,
 6,
 159,
 3654856,
 1,
 13,
 163,
 3654861,
 1,
 2,
 167,
 3654863,
 1,
 171,
 13,
 0,
 99,
 2,
 0,
 14,
 0]